### ISSUE TITLE
Unathorized client sercet

### ISSUE THREAD

**Issue by philm001** [ckhmer1/node-red-contrib-alexa-virtual-smarthome#5]
When I go to perform the LWA with my account, I get this error:

Unauthorized client_secret

Now, I triple checked the values that I was placing in. I checked to make sure that I placed in the correct "Your Client ID" and "Your Secret" values in the correct boxes in the config and in the endpoint. But when I do the LWA, the result in unable to link Smart Home

Do you know what might also be causing this error?

**Comment by ckhmer1** [comment]
Could You please follow the troubleshooting instructions and post here the results?

**Comment by philm001** [comment]
So I was able to run the troubleshooting instructions and the setup passed the tests except for the linking to my amazon account. I am copying the output of the NODE red console here:

```
AlexaAdapterNode:oauth_get
AlexaAdapterNode:oauth_get CCHI {"code":"ANTQDYARwjTHPzbuLnqD","scope":"profile"}
13 Dec 14:05:18 - [error] [alexa-adapter:Alexa] oauth_get profile
AlexaAdapterNode:manage_login_with_amazon_access_token
AlexaAdapterNode:manage_login_with_amazon_access_token CCHI config {"id":"b6996b92647b12f3","type":"alexa-adapter","name":"Alexa","http_path":"alexa","login_with_amazon":true,"event_endpoint":"https://api.amazonalexa.com/v3/events","scope":"smart_home","emails":["***@gmail.com"],"msg_check":false,"verbose":true,"port":"","_users":["47c54cce05a7162a","9d730dee04a484b7"]}
AlexaAdapterNode:manage_login_with_amazon_access_token CCHI credentials {"your_client_id":"NodeRedAlexaRV","your_secret":"password","oa2_client_id":"amzn1.application-oa2-client.9283145f821e458097564e6bbbd8aabb","oa2_secret":"44ef5c74c58333e58a9f7a6cdc2246df413236ecbcd100170c4935d04d12001e","skill_client_id":"amzn1.application-oa2-client.9715a407aaa5440da726c8b208617175","skill_secret":"8e10cd9ebd096209f9a7ad1eb7e58f13d8c1f5e496af0888b382f644aea17e2e"}
AlexaAdapterNode:get_access_token lwa
AlexaAdapterNode:get_access_token request with code
AlexaAdapterNode:get_access_token request {"grant_type":"authorization_code","code":"ANTQDYARwjTHPzbuLnqD","redirect_uri":"https://alexatest2.ddns.net/alexa/oauth"}
AlexaAdapterNode:CCHI get_access_token res {"req":{"method":"POST","url":"https://api.amazon.com/auth/o2/token","data":{"grant_type":"authorization_code","code":"ANTQDYARwjTHPzbuLnqD","redirect_uri":"https://alexatest2.ddns.net/alexa/oauth"},"headers":{"user-agent":"node-superagent/3.8.3","content-type":"application/x-www-form-urlencoded","authorization":"Basic YW16bjEuYXBwbGljYXRpb24tb2EyLWNsaWVudC45MjgzMTQ1ZjgyMWU0NTgwOTc1NjRlNmJiYmQ4YWFiYjo0NGVmNWM3NGM1ODMzM2U1OGE5ZjdhNmNkYzIyNDZkZjQxMzIzNmVjYmNkMTAwMTcwYzQ5MzVkMDRkMTIwMDFl"}},"header":{"server":"Server","date":"Mon, 13 Dec 2021 19:05:19 GMT","content-type":"application/json;charset=UTF-8","content-length":"934","connection":"close","x-amz-rid":"F6KKVR26AWW6PT431WKT","x-amzn-requestid":"2798f022-46b4-41cd-afd4-883e5cec8a59","x-amz-date":"Mon, 13 Dec 2021 19:05:19 GMT","cache-control":"no-cache, no-store, must-revalidate","pragma":"no-cache","vary":"Content-Type,Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent","permissions-policy":"interest-cohort=()"},"status":200,"text":"{\"access_token\":\"Atza|IwEBIMHhODQqiVcpf1zvI24U48qUM_q_D-PXn0oKIJk5mq9_03RRwkaFt21uyRcdDHZWk-DkreHqPKiJJa2VO1wFQev38T3_WLWr7jZAnjAsZvGzyixVckCYoqjjaDyTJIRrKb1U9iKZc95meFeSWiRENjeoIlbrxvuGecNjJ7MVqLQ0z4zLqoq6Q_7XvCupaBIOptGZRkSOx8UUaQd8AbZfoFngqhXdyUfIWGwkmq92kod3WCXNNB26AHvGnieCVYEr2EtcCj73gKJaWLAX5KsVKdw3Z5NCU2VEFkQWWdGKjK7pplRH7qPzCwShffAT9oZI5S8DHq8eEs71lWgj-xyW6AtN-73HxrTFl46o2dzSOfk_FerDStVMjMyPduMduAMl7MG3FDwNOfEGDUcRZ2DTz4FfI0KyDBW3NPkNE606gueG7g\",\"refresh_token\":\"Atzr|IwEBIG61rBWuHO8qZ6c_YIBl8Rlhteq0Eg7mTwWweIa9S_euyOG6lxXonaUJ9XqRD0JgmBpxKykYDtLoWDN7eO42Is1dkKzZ1ZrHJAR8Vr3Of4jQTfrPLE55ixLZLa5Q1JBbIyJphXK_DzO3HsaUctTXahJCNTPnyyYk1etGJi3cVtAB2nI6kTOu35GXVZGfA3ArtOLefMWs1Ort1kS5X0IgdjXVm-wEiPVtyQk4SF3p9_EAhT6ccj4LpOBqjHWBTteetz1Kboo1Bfj9PTrLLE7AY8tJAcODyFbEBg-S_T6ycejrG1OqnLfI0fxTNmcVgvgshOQLje3trJkb3ZXMYW4XvnIRU3_mHC-a2dFSiXmtKZOISvFkjdnpueF9QoWICtg0Q1WLUO9D1LWvbDz1Jk46aM97\",\"token_type\":\"bearer\",\"expires_in\":3600}"}
AlexaAdapterNode:writeJson: tokens
AlexaAdapterNode:writeJson: filename /home/pi/.node-red/alexa-tokens_b6996b92647b12f3.json
AlexaAdapterNode:writeJson: tokens saved
AlexaAdapterNode:get_access_token tokens lwa saved
AlexaAdapterNode:mlwaat get_access_token CCHI res Atza|IwEBIMHhODQqiVcpf1zvI24U48qUM_q_D-PXn0oKIJk5mq9_03RRwkaFt21uyRcdDHZWk-DkreHqPKiJJa2VO1wFQev38T3_WLWr7jZAnjAsZvGzyixVckCYoqjjaDyTJIRrKb1U9iKZc95meFeSWiRENjeoIlbrxvuGecNjJ7MVqLQ0z4zLqoq6Q_7XvCupaBIOptGZRkSOx8UUaQd8AbZfoFngqhXdyUfIWGwkmq92kod3WCXNNB26AHvGnieCVYEr2EtcCj73gKJaWLAX5KsVKdw3Z5NCU2VEFkQWWdGKjK7pplRH7qPzCwShffAT9oZI5S8DHq8eEs71lWgj-xyW6AtN-73HxrTFl46o2dzSOfk_FerDStVMjMyPduMduAMl7MG3FDwNOfEGDUcRZ2DTz4FfI0KyDBW3NPkNE606gueG7g
AlexaAdapterNode:get_user_profile CCHI access_token res {"access_token":"Atza|IwEBIMHhODQqiVcpf1zvI24U48qUM_q_D-PXn0oKIJk5mq9_03RRwkaFt21uyRcdDHZWk-DkreHqPKiJJa2VO1wFQev38T3_WLWr7jZAnjAsZvGzyixVckCYoqjjaDyTJIRrKb1U9iKZc95meFeSWiRENjeoIlbrxvuGecNjJ7MVqLQ0z4zLqoq6Q_7XvCupaBIOptGZRkSOx8UUaQd8AbZfoFngqhXdyUfIWGwkmq92kod3WCXNNB26AHvGnieCVYEr2EtcCj73gKJaWLAX5KsVKdw3Z5NCU2VEFkQWWdGKjK7pplRH7qPzCwShffAT9oZI5S8DHq8eEs71lWgj-xyW6AtN-73HxrTFl46o2dzSOfk_FerDStVMjMyPduMduAMl7MG3FDwNOfEGDUcRZ2DTz4FfI0KyDBW3NPkNE606gueG7g"}
AlexaAdapterNode:get_user_profile CCHI profile res {"req":{"method":"GET","url":"https://api.amazon.com/user/profile","headers":{"user-agent":"node-superagent/3.8.3","authorization":"Bearer Atza|IwEBIMHhODQqiVcpf1zvI24U48qUM_q_D-PXn0oKIJk5mq9_03RRwkaFt21uyRcdDHZWk-DkreHqPKiJJa2VO1wFQev38T3_WLWr7jZAnjAsZvGzyixVckCYoqjjaDyTJIRrKb1U9iKZc95meFeSWiRENjeoIlbrxvuGecNjJ7MVqLQ0z4zLqoq6Q_7XvCupaBIOptGZRkSOx8UUaQd8AbZfoFngqhXdyUfIWGwkmq92kod3WCXNNB26AHvGnieCVYEr2EtcCj73gKJaWLAX5KsVKdw3Z5NCU2VEFkQWWdGKjK7pplRH7qPzCwShffAT9oZI5S8DHq8eEs71lWgj-xyW6AtN-73HxrTFl46o2dzSOfk_FerDStVMjMyPduMduAMl7MG3FDwNOfEGDUcRZ2DTz4FfI0KyDBW3NPkNE606gueG7g","content-type":"application/x-www-form-urlencoded;charset=UTF-8","accept":"application/json"}},"header":{"server":"Server","date":"Mon, 13 Dec 2021 19:05:19 GMT","content-type":"application/json;charset=UTF-8","content-length":"115","connection":"close","x-amz-rid":"8SG7FFTNQ35JPE8G5EZJ","x-amzn-requestid":"d5935cc1-ec9b-40fe-902a-2cfff7d83f5f","x-amz-date":"Mon, 13 Dec 2021 19:05:19 GMT","content-language":"en-US","vary":"Content-Type,Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent","permissions-policy":"interest-cohort=()"},"status":200,"text":"{\"user_id\":\"amzn1.account.AGBCE2ITIGEQNHWMFIRL6QFU3DVQ\",\"name\":\"*** ***\",\"email\":\"***@gmail.com\"}"}
AlexaAdapterNode:get_user_profile CCHI res {"user_id":"amzn1.account.AGBCE2ITIGEQNHWMFIRL6QFU3DVQ","name":"John Doe","email":"***@gmail.com"}
AlexaAdapterNode:***@gmail.com OK
13 Dec 14:05:19 - [error] [alexa-adapter:Alexa] Username ***@gmail.com authorized
AlexaAdapterNode:manage_login_with_amazon_access_token CCHI auth_code {"code":"6VCqUJaiGZZDL3RTiqq41H11CxJh6HCRLpBz5Nx19JYw","expire_at":1639422439308}
AlexaAdapterNode:redirect_to_amazon to https://pitangui.amazon.com/api/skill/link/M186UMMFQ858RV?state=A2SAAEAEIkbZ8rdEKhe62zTmbcE7RcB4I1V1H648LHFVSi2ZhxYPrpKxo1ZXhJH47xlL7X6EN2ng34Q6jIEXL4uYCrJ18-mvo3SYhlorXJx7jf9mZXtnM1-uxbJkP7bgrBD2qDDPAR96Pzo-f4-Qn35Ws09qRZmPXQFnlnfu9hQ_UHY5cAqh0QXEnQWIOXVlgpNBLaLwVLwdfPHU8TizfyThWWSVjB3j01G5giGqih12pncvPTvRw4zIpQNl9BH9Fw2dVjvZ5dTn4oh1BdytHDPIqARYeNR7s_fPhFnqfzpvV1ScZaUHeupJsKYNQIFtfQiZVYvrGftB6pXAMKVF7A5AuaCNAAo7-taF6CJUkaH6UrG1uqaR2OXC7tL7Y_uI-qowouNpYaW_Qgl72BD9MHqB6VHGoyKJxYz_TXbScgGR1L3y__ff8YyKzcRlN-MGwkMaRMWYH0j1TxfIzVotUmLUzWiDhs2mk7C715M026BYMYl8vkQ_pb5c8iDdN2UZ_H8z49Pv6wDRLPIWXyviS68iOb3_FySw5xRvriPo2nt7v16mtqq25o2n8N9qNJbNmDedO8D-IkqgCOaDKz48yQcSCyz9D22Ob4x8bd9ArgsiCvxB4rA63H3y7V4l7vMn-0WFLWNtiGE7L8m67YlUzFU4mndkKfVJA&code=6VCqUJaiGZZDL3RTiqq41H11CxJh6HCRLpBz5Nx19JYw
AlexaAdapterNode:token_post
AlexaAdapterNode:token_post CCHI {"grant_type":"authorization_code","code":"6VCqUJaiGZZDL3RTiqq41H11CxJh6HCRLpBz5Nx19JYw","client_id":"NodeRedAlexaRV","redirect_uri":"https://pitangui.amazon.com/api/skill/link/M186UMMFQ858RV"}
13 Dec 14:05:19 - [error] [alexa-adapter:Alexa] token_post authorization_code
13 Dec 14:05:19 - [error] [alexa-adapter:Alexa] Unauthorized client_secret
```

**Comment by philm001** [comment]
Hello, to give an update, I re-went through the entire tutorial again and I copied all of the client secrets and IDs. I now get the message of successful authentication. However, on the account page, I still get a message saying that the skill was unable to link to my account

The error states: We are unable to link SmartHomeApp at this time. Is there anything else that I am suppose to do?

**Comment by ckhmer1** [comment]
Did You install the latest version of the Alexa node? I've just released a fix yesterday.
I've also repeated all the setup instructions and I'm able to link the account.

**Comment by philm001** [comment]
I did not, will give that a try and let you know. thank you

**Comment by philm001** [comment]
I have updated and attempted the same account linking command. I am still unable to link account

**Comment by ckhmer1** [comment]
Could You please post the logs?

**Comment by philm001** [comment]
Here are the logs

```
4:22:58 PM - [debug] [alexa-adapter:Alexa] oauth_get
4:22:58 PM - [debug] [alexa-adapter:Alexa] oauth_get CCHI {"code":"ANbmCqCvHblgPsNYpfOu","scope":"profile"}
14 Dec 16:22:58 - [error] [alexa-adapter:Alexa] oauth_get profile
4:22:58 PM - [debug] [alexa-adapter:Alexa] manage_login_with_amazon_access_token
4:22:58 PM - [debug] [alexa-adapter:Alexa] manage_login_with_amazon_access_token CCHI config {"id":"b6996b92647b12f3","type":"alexa-adapter","name":"Alexa","http_path":"/alexa/","login_with_amazon":true,"event_endpoint":"https://api.amazonalexa.com/v3/events","scope":"smart_home","emails":["phillipmobley2@gmail.com"],"msg_check":false,"verbose":true,"port":"","_users":["47c54cce05a7162a","9d730dee04a484b7"]}
4:22:58 PM - [debug] [alexa-adapter:Alexa] manage_login_with_amazon_access_token CCHI credentials {"your_client_id":"NodeRedAlexaRV","your_secret":"supersecretpassword","oa2_client_id":"amzn1.application-oa2-client.9283145f821e458097564e6bbbd8aabb","oa2_secret":"44ef5c74c58333e58a9f7a6cdc2246df413236ecbcd100170c4935d04d12001e","skill_client_id":"amzn1.application-oa2-client.56b9c72428544026a6e419b0c9d23a39","skill_secret":"a7a0b690c8b1a43e890bd2c6f26463551ba430919ec298de08ed1a58623c3fb2"}
4:22:58 PM - [debug] [alexa-adapter:Alexa] get_access_token lwa
4:22:58 PM - [debug] [alexa-adapter:Alexa] get_access_token request with code
4:22:58 PM - [debug] [alexa-adapter:Alexa] get_access_token request {"grant_type":"authorization_code","code":"ANbmCqCvHblgPsNYpfOu","redirect_uri":"https://alexatest2.ddns.net/alexa/oauth"}
4:22:58 PM - [debug] [alexa-adapter:Alexa] CCHI get_access_token res {"req":{"method":"POST","url":"https://api.amazon.com/auth/o2/token","data":{"grant_type":"authorization_code","code":"ANbmCqCvHblgPsNYpfOu","redirect_uri":"https://alexatest2.ddns.net/alexa/oauth"},"headers":{"user-agent":"node-superagent/3.8.3","content-type":"application/x-www-form-urlencoded","authorization":"Basic YW16bjEuYXBwbGljYXRpb24tb2EyLWNsaWVudC45MjgzMTQ1ZjgyMWU0NTgwOTc1NjRlNmJiYmQ4YWFiYjo0NGVmNWM3NGM1ODMzM2U1OGE5ZjdhNmNkYzIyNDZkZjQxMzIzNmVjYmNkMTAwMTcwYzQ5MzVkMDRkMTIwMDFl"}},"header":{"server":"Server","date":"Tue, 14 Dec 2021 21:22:58 GMT","content-type":"application/json;charset=UTF-8","content-length":"956","connection":"close","x-amz-rid":"YDRMMYN3ENZJ40GXWV0D","x-amzn-requestid":"562f2c0d-8520-46db-819d-f4fb24723c6e","x-amz-date":"Tue, 14 Dec 2021 21:22:58 GMT","cache-control":"no-cache, no-store, must-revalidate","pragma":"no-cache","vary":"Content-Type,Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent","permissions-policy":"interest-cohort=()"},"status":200,"text":"{\"access_token\":\"Atza|IwEBIMhsfjLoJsqQcxXsLpPWKglJ_h7fm2pybvlo1VwOOA0uVajP3kgMh6-Q43xy8wqtIvr4MfcsF0_Gb03MdbSlj7G2SHDFKlO-ViQRB2Lhey1ZuxIivQyquNAVGuGuBQuD4BSVBIWewDBVxVW0-gtxzG1ltkE0XS5CrFFMG_umxdb3dUh6QuHkV2idEFJrQllMBvCf6FEMWTo88VGWTI2QAFL0_knKI_-LQYlL3LhlCWb2Ekw99HCOGS9Xe-iUbB0nDoUIGaga43FDoBGVqyga9KJrvjcK1J0VeC_L07KjS-mcPyHSlPxRyoY_jxRVOpZynvEaXflzsYihF9T_tAEhfw7EzSR0KfHxd1xSjMTHwHnwZdpiGqWzXC036wyn96igeaWeps5jlSMYsI9J7kMsfI-bSeeMfpNqDkLKFH_IvFZyvw\",\"refresh_token\":\"Atzr|IwEBIAGKaGmHh--P1hpT44y67JiiL1z9i68FdeLHS5EYIwoJys-5Zybbov5y9SOYIvfoOKgFXiDO9AaZj0uQknoF2iLJxmp70Ixxu5Co0pWKcnhNUARWUBOgkxRNvoJjHSEiiNKZaUIZZ0rM-aEX7W1YD5QJ9HLfieoT5WWGYmYo6GEPeu1jmH1D3fnXu6kJrybVO7_64JhgCUNUuJ8ICbunsvcUO5C2yywMO0649vR5SpXtEW88PuSvolonJ6I3OC8CHZ2cNtpbrFwSbbMSxgKbvVUiUvyHj-XnZmW6gdfZx7Ppk0vrEeaN7DQHK3a6pgzriA8CExdoUafEDIswGLoNy-TYtcAC8SDSG1GmBEZ4FFX5i-4KLlyAi4xeX_gMjeg3qIrRhHpvsO_NuSLZ89DtRJs-DYyUHnJiR0ksfSaLRykFIw\",\"token_type\":\"bearer\",\"expires_in\":3600}"}
4:22:58 PM - [debug] [alexa-adapter:Alexa] writeJson: tokens
4:22:58 PM - [debug] [alexa-adapter:Alexa] writeJson: filename /home/pi/.node-red/alexa-tokens_b6996b92647b12f3.json
4:22:58 PM - [debug] [alexa-adapter:Alexa] writeJson: tokens saved
4:22:58 PM - [debug] [alexa-adapter:Alexa] get_access_token tokens lwa saved
4:22:58 PM - [debug] [alexa-adapter:Alexa] mlwaat get_access_token CCHI res Atza|IwEBIMhsfjLoJsqQcxXsLpPWKglJ_h7fm2pybvlo1VwOOA0uVajP3kgMh6-Q43xy8wqtIvr4MfcsF0_Gb03MdbSlj7G2SHDFKlO-ViQRB2Lhey1ZuxIivQyquNAVGuGuBQuD4BSVBIWewDBVxVW0-gtxzG1ltkE0XS5CrFFMG_umxdb3dUh6QuHkV2idEFJrQllMBvCf6FEMWTo88VGWTI2QAFL0_knKI_-LQYlL3LhlCWb2Ekw99HCOGS9Xe-iUbB0nDoUIGaga43FDoBGVqyga9KJrvjcK1J0VeC_L07KjS-mcPyHSlPxRyoY_jxRVOpZynvEaXflzsYihF9T_tAEhfw7EzSR0KfHxd1xSjMTHwHnwZdpiGqWzXC036wyn96igeaWeps5jlSMYsI9J7kMsfI-bSeeMfpNqDkLKFH_IvFZyvw
4:22:58 PM - [debug] [alexa-adapter:Alexa] get_user_profile CCHI access_token res {"access_token":"Atza|IwEBIMhsfjLoJsqQcxXsLpPWKglJ_h7fm2pybvlo1VwOOA0uVajP3kgMh6-Q43xy8wqtIvr4MfcsF0_Gb03MdbSlj7G2SHDFKlO-ViQRB2Lhey1ZuxIivQyquNAVGuGuBQuD4BSVBIWewDBVxVW0-gtxzG1ltkE0XS5CrFFMG_umxdb3dUh6QuHkV2idEFJrQllMBvCf6FEMWTo88VGWTI2QAFL0_knKI_-LQYlL3LhlCWb2Ekw99HCOGS9Xe-iUbB0nDoUIGaga43FDoBGVqyga9KJrvjcK1J0VeC_L07KjS-mcPyHSlPxRyoY_jxRVOpZynvEaXflzsYihF9T_tAEhfw7EzSR0KfHxd1xSjMTHwHnwZdpiGqWzXC036wyn96igeaWeps5jlSMYsI9J7kMsfI-bSeeMfpNqDkLKFH_IvFZyvw"}
4:22:59 PM - [debug] [alexa-adapter:Alexa] get_user_profile CCHI profile res {"req":{"method":"GET","url":"https://api.amazon.com/user/profile","headers":{"user-agent":"node-superagent/3.8.3","authorization":"Bearer Atza|IwEBIMhsfjLoJsqQcxXsLpPWKglJ_h7fm2pybvlo1VwOOA0uVajP3kgMh6-Q43xy8wqtIvr4MfcsF0_Gb03MdbSlj7G2SHDFKlO-ViQRB2Lhey1ZuxIivQyquNAVGuGuBQuD4BSVBIWewDBVxVW0-gtxzG1ltkE0XS5CrFFMG_umxdb3dUh6QuHkV2idEFJrQllMBvCf6FEMWTo88VGWTI2QAFL0_knKI_-LQYlL3LhlCWb2Ekw99HCOGS9Xe-iUbB0nDoUIGaga43FDoBGVqyga9KJrvjcK1J0VeC_L07KjS-mcPyHSlPxRyoY_jxRVOpZynvEaXflzsYihF9T_tAEhfw7EzSR0KfHxd1xSjMTHwHnwZdpiGqWzXC036wyn96igeaWeps5jlSMYsI9J7kMsfI-bSeeMfpNqDkLKFH_IvFZyvw","content-type":"application/x-www-form-urlencoded;charset=UTF-8","accept":"application/json"}},"header":{"server":"Server","date":"Tue, 14 Dec 2021 21:22:59 GMT","content-type":"application/json;charset=UTF-8","content-length":"115","connection":"close","x-amz-rid":"2M90ZP3AEFW5GSQR2CKC","x-amzn-requestid":"f1a1ff4f-0186-4c2b-9bf6-5c2f28dd8873","x-amz-date":"Tue, 14 Dec 2021 21:22:59 GMT","content-language":"en-US","vary":"Content-Type,Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent","permissions-policy":"interest-cohort=()"},"status":200,"text":"{\"user_id\":\"amzn1.account.AGBCE2ITIGEQNHWMFIRL6QFU3DVQ\",\"name\":\"phillip mobley\",\"email\":\"phillipmobley2@gmail.com\"}"}
4:22:59 PM - [debug] [alexa-adapter:Alexa] get_user_profile CCHI res {"user_id":"amzn1.account.AGBCE2ITIGEQNHWMFIRL6QFU3DVQ","name":"phillip mobley","email":"phillipmobley2@gmail.com"}
4:22:59 PM - [debug] [alexa-adapter:Alexa] phillipmobley2@gmail.com OK
14 Dec 16:22:59 - [error] [alexa-adapter:Alexa] Username phillipmobley2@gmail.com authorized
4:22:59 PM - [debug] [alexa-adapter:Alexa] manage_login_with_amazon_access_token CCHI auth_code {"code":"G6uBMpZWwLTzGBb8DchcH9oxY6qeuwVsriVzsW926hzm","expire_at":1639517099032}
4:22:59 PM - [debug] [alexa-adapter:Alexa] redirect_to_amazon to https://pitangui.amazon.com/api/skill/link/M186UMMFQ858RV?state=A2SAAEAEMD2gUhrLtsJ3aDSlo4vT6MB8GgKFLtm8mwIdIzIAy555NoKBrxegrKSwFMZPmdwKlqHw-hzy3S2sjaTjIaAyGud8TEHmSMPSVNiqHG93v-FjwdnVToGO420aOFJ05bv_0zH9CpdYWcMiVFPTWJM2XOoONOwSBOJjg83jt4JhzUN1a2Z7IOwYOFWk8n7rL31j4OpX8XoP8s9-xU9p8X3c7BHpjU_CPjNGiEb3lDV7q5Tr8uVLX7hce8b607ZeLBEK_e_3ozDbt0eNRmwxmQKEDus48ssdRZOk74MFkYZLEQSlY4imDOz3x6d2jhDn3bVo2MYKmB3JngA5ydS5Y8w3aCBfvUWpA4iW_UMHkrJUP2oGm7snbLbGr_nqOCngsoDGN7Z2Fsx-HFDcxQItBaiIReJjKQZRIteYcZGZh_v3EOjFfOUiZ2-Bmdfo8ezmOi4X5BN-9GIhrWTo9IQ8bVxJykvKq2XtQl7PGeHmdIVUPBlrFP3cKLJ43eYgKB34AFxPW8i3GwS7K_tBC9G6ugaxmbtkSVk-dzFmel76UaxWpCY4V3PM5-iAKX0JX05f9X7P6C1_Azbwz_K4Yxm6YgcASulFgdYecrs6m1P3YqSLUI12COHbdoyhBJm9EVwd9zmB-7ZE39jTUydX2hty12SpPszwN3HqyQU-7YCl993-Yj0JyU&code=G6uBMpZWwLTzGBb8DchcH9oxY6qeuwVsriVzsW926hzm
4:22:59 PM - [debug] [alexa-adapter:Alexa] token_post
4:22:59 PM - [debug] [alexa-adapter:Alexa] token_post CCHI {"grant_type":"authorization_code","code":"G6uBMpZWwLTzGBb8DchcH9oxY6qeuwVsriVzsW926hzm","client_id":"NodeRedAlexaRV","redirect_uri":"https://pitangui.amazon.com/api/skill/link/M186UMMFQ858RV","client_secret":"supersecretpassword"}
14 Dec 16:22:59 - [error] [alexa-adapter:Alexa] token_post authorization_code
4:22:59 PM - [debug] [alexa-adapter:Alexa] writeJson: tokens
4:22:59 PM - [debug] [alexa-adapter:Alexa] writeJson: filename /home/pi/.node-red/alexa-tokens_b6996b92647b12f3.json
4:22:59 PM - [debug] [alexa-adapter:Alexa] writeJson: tokens saved
4:22:59 PM - [debug] [alexa-adapter:Alexa] token_post save_tokens ok
4:22:59 PM - [debug] [alexa-adapter:Alexa] Returns tokens
4:22:59 PM - [debug] [alexa-adapter:Alexa] Returns tokens {"access_token":"Atza|GAwmmRd8fiVPTgbd17nhrUzj8o9aEYanggCozMJBxAyU","token_type":"bearer","expires_in":3600,"refresh_token":"Atzr|BrtpofxDrTG7HZVTjk7KboZBivjVRW7XdvdkQa6VvzCj"}
```

**Comment by ckhmer1** [comment]
I see from the log that now Your client secret is recognized correctly and Node-RED Alexa smart home returns correctly the access token but the lambda function doesn't get called.

Did You configure the lambda function in the correct region?

**Comment by philm001** [comment]
I created the lambda function the N. Virginia region which is the next closest region that supports the lambda Alexa Smart home trigger (Note: I would highly recommend putting a note in the instructions to state that the region for the lambda server needs to support the Alexa Smart Home trigger).

I ran the test script for the lambda server on the correct region one and I do get back the correct response. 

What parts of the Alexa need to be on the same region? I have the lambda server on the N Virginia region and everything else on the Ohio region. Is that acceptable?

I will take a detailed look at the settings for the alexa skill and the lambda server to make sure everything is good. 

Is there anyway for me to test if the Node red application can communicate with the lambda server?

**Comment by philm001** [comment]
I should also note that I have a EC2 server that is handling nginx on the Ohio region. Does this server instance also need to be in the same region as the lambda server?

**Comment by ckhmer1** [comment]
I'm sorry, I'm not an aws expert.
Could you please tell me how to add connected a cloud watch to the lambda server? I'd like to add it in the troubleshooting section.

Finally have you succeed to link the skill? From the Node-RED log out seen so.

**Comment by philm001** [comment]
Sure, I can tell you once I solve this issue

I am unable to link the skill. I as hoping you would be able to assist me

**Comment by philm001** [comment]
When I click on the linking, I get this error:

We were unable to link TestSmartHomeSkill at this time. 

I copied and pasted all of the values in the instructions into my device settings. There was a change on the Alexa skill id. I do not think that Alexa is sending a discovery message if you look through the logs

**Comment by philm001** [comment]
![Error](https://user-images.githubusercontent.com/13646291/146259610-b911521e-34da-4942-8c44-17832392232b.JPG)

**Comment by philm001** [comment]
```
node.get_access_token('evn', payload.grant.code)
                    .then(() => {
                        if (node.config.verbose) node._debug("accept_grant tokens evn OK");
                        const ok_response = {
                            event: {
                                header: {
                                    namespace: "Alexa.Authorization",
                                    name: "AcceptGrant.Response",
                                    messageId: node.tokgen.generate(),
                                    payloadVersion: PAYLOADS_VERSION['Alexa.Authorization'] || DEFAULT_PAYLOAD_VERSION
                                },
                                payload: {}
                            }
                        };
                        res.json(ok_response);
                        res.end();
                    })
```

So here I am assuming that this is the post that the node sends out to the Alexa servers? How do I know that it was sent correctly?

**Comment by philm001** [comment]
I get this link but it fails each time:

https://pitangui.amazon.com/api/skill/link/M186UMMFQ858RV?state=A2SAAEAEFfdNEG-LyjlfONIKhOVCkcB8F7OjrNztLxxlBW1A7_W9Rfntu345yL9PP3eSShsXmyIAl7AJwjukLJINaXI6zPGfHVBpOit0aoWWq0hmx5AtAQQ21BQ3GdaC5VWhQnVEN8gFVnJEEb2zuCQJvOLqD48qp3De0X9vI_JvZuqi1tEUSDOFH39KTqfNk4pK0ozMB-ogYaKMU2uyX8v3G_C6c1YSgeBMUZqkxtZEmEjSQTqQNm51HMDHlRDVYd_4-VjeHCk70Y_Dr8OezsePww47BT5NH2bjk5bnpvHeKKb23_G7OuADWxDSU2SVdEpVmTTAJGNitrtwRF5f5cFEi_g65biDeGtjiQuEVUuvHeEFNqq5-8TXWcSOJld9YxA-XrP56wdt_VH3Af9z4Q6sbBM6vrsWJFgbRcpdtkH01gIrhEqBOl3BYXLtQ5Iy9acIVuKk6ywdTdQWcw2j3tMnTPTp6_wKhepb8NMD58aTu8DH3Zd_Bm3vUW-fISbQNqbbkMLiIBJcXd3LDewXPV1L8gpl8cIO3G571ExQHPyDrTbV_Bfa5CgCHk7oDW7iJT5T6rZbgRYGTgmCK7zj33CWh7koSmL6g1fJ3jkLZfHFp9RYTm8DgN2z0tiftbNH-DAQ_8YVbB-gajqeTLu0Qo2RRqRt_CJZJ7ksPTEyfl1hcD9CZN-T1Y&code=1DZU4LDkPkUhc88BDN5LPxQbPdtkQZvrVeyGbD6E4BXe

**Comment by philm001** [comment]
```
4:59:15 PM - [debug] [alexa-adapter:Alexa] oauth_get
4:59:15 PM - [debug] [alexa-adapter:Alexa] oauth_get CCHI {"code":"ANuWvQoRiInPXsdjlmZd","scope":"profile"}
15 Dec 16:59:15 - [error] [alexa-adapter:Alexa] oauth_get profile
4:59:15 PM - [debug] [alexa-adapter:Alexa] manage_login_with_amazon_access_token
4:59:15 PM - [debug] [alexa-adapter:Alexa] manage_login_with_amazon_access_token CCHI config {"id":"b6996b92647b12f3","type":"alexa-adapter","name":"Alexa","http_path":"alexa","login_with_amazon":true,"event_endpoint":"https://api.amazonalexa.com/v3/events","scope":"smart_home","emails":["phillipmobley2@gmail.com"],"msg_check":true,"verbose":true,"port":"","_users":["47c54cce05a7162a","9d730dee04a484b7"]}
4:59:15 PM - [debug] [alexa-adapter:Alexa] manage_login_with_amazon_access_token CCHI credentials {"your_client_id":"https://pitangui.amazon.com/","your_secret":"supersercetpassword","oa2_client_id":"amzn1.application-oa2-client.9283145f821e458097564e6bbbd8aabb","oa2_secret":"44ef5c74c58333e58a9f7a6cdc2246df413236ecbcd100170c4935d04d12001e","skill_client_id":"amzn1.application-oa2-client.56b9c72428544026a6e419b0c9d23a39","skill_secret":"a7a0b690c8b1a43e890bd2c6f26463551ba430919ec298de08ed1a58623c3fb2"}
4:59:15 PM - [debug] [alexa-adapter:Alexa] get_access_token lwa
4:59:15 PM - [debug] [alexa-adapter:Alexa] get_access_token request with code
4:59:15 PM - [debug] [alexa-adapter:Alexa] get_access_token request {"grant_type":"authorization_code","code":"ANuWvQoRiInPXsdjlmZd","redirect_uri":"https://alexatest2.ddns.net/alexa/oauth"}
4:59:15 PM - [debug] [alexa-adapter:Alexa] CCHI get_access_token res {"req":{"method":"POST","url":"https://api.amazon.com/auth/o2/token","data":{"grant_type":"authorization_code","code":"ANuWvQoRiInPXsdjlmZd","redirect_uri":"https://alexatest2.ddns.net/alexa/oauth"},"headers":{"user-agent":"node-superagent/3.8.3","content-type":"application/x-www-form-urlencoded","authorization":"Basic YW16bjEuYXBwbGljYXRpb24tb2EyLWNsaWVudC45MjgzMTQ1ZjgyMWU0NTgwOTc1NjRlNmJiYmQ4YWFiYjo0NGVmNWM3NGM1ODMzM2U1OGE5ZjdhNmNkYzIyNDZkZjQxMzIzNmVjYmNkMTAwMTcwYzQ5MzVkMDRkMTIwMDFl"}},"header":{"server":"Server","date":"Wed, 15 Dec 2021 21:59:15 GMT","content-type":"application/json;charset=UTF-8","content-length":"912","connection":"close","x-amz-rid":"X34GRT7Q9NC8Y0E6YYCV","x-amzn-requestid":"89a41a37-fcb7-4743-903e-546d327e4335","x-amz-date":"Wed, 15 Dec 2021 21:59:15 GMT","cache-control":"no-cache, no-store, must-revalidate","pragma":"no-cache","vary":"Content-Type,Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent","permissions-policy":"interest-cohort=()"},"status":200,"text":"{\"access_token\":\"Atza|IwEBIEiRM6UmfMQ-3H5BcUXXbQjU2fHSpPOrruMgqGZYqrQIIcNWGlnUZAP-zAXSvXZwylJfoaPgW_4q99rQZC3aNVmSvWpC1xZFPqYBwTZ0vg6NkYCg60BS7Tt2EHQb2llwjV_9aqjHW58BTpR7Z_pYP8EBqqqfLEcGCTfGjhXgxn5YDBytjh6OIXgkrK5b8sUhPYo9EHWCmvT3JusTRm-CrodIgfVOsnJLMWXQZim5iXKqiPm3rdmh0EXBdQ9qRU40zMO6LYl0XW2sMDKaKdjeoTJFDPL9RlWeJ4k-ZlXR7uBOamCNbZotxSHl3-DbJJI7TDkWJ9nqH8rj-Dalrpi6CvBvged7sj2ywwLSxrp-l2FDmhY-OUkonBKNNZNc6m5uweJ6De7KJrc-S9DfT2epMhzV\",\"refresh_token\":\"Atzr|IwEBIGiqb3QE7Lhcyl6EOn3BKsdQDYmbm1sCwd5QnDoe-edhQMn6hMGpikfeAapmPLHU6Bmyj6vf9t2Gv9OO5Bzt1D8zNWmsNqkatM_AhEBtgmmDcsAr-oULs4nnLe0S0SrW_ucUgUt5EHVgwX0r6cmJWvP3Wtv-IdIUG_DRdU5OMljrXXfxszezjnYnyHoyX-dxqH9stcEV5BD-YrPfY1BBLF1ys9OpsH0IOKWD2OOgc3gl9IsmSbi0r6RPThz68eEn3XmJGoy4Va2OukAHbw0Co-THeX5EcyMkfwtsz8K5qgxXmkifNfrThC5O5SVBQ0q138wB2F9dhSOHEAITBQ9lh6AC4_oOlyjnkytwLgWarNSDvxiLrHTuMIgCc3O92LVjalfJT2kUfxjfay73V2cUknKY\",\"token_type\":\"bearer\",\"expires_in\":3600}"}
4:59:15 PM - [debug] [alexa-adapter:Alexa] writeJson: tokens
4:59:15 PM - [debug] [alexa-adapter:Alexa] writeJson: filename /home/pi/.node-red/alexa-tokens_b6996b92647b12f3.json
4:59:15 PM - [debug] [alexa-adapter:Alexa] writeJson: tokens saved
4:59:15 PM - [debug] [alexa-adapter:Alexa] get_access_token tokens lwa saved
4:59:15 PM - [debug] [alexa-adapter:Alexa] mlwaat get_access_token CCHI res Atza|IwEBIEiRM6UmfMQ-3H5BcUXXbQjU2fHSpPOrruMgqGZYqrQIIcNWGlnUZAP-zAXSvXZwylJfoaPgW_4q99rQZC3aNVmSvWpC1xZFPqYBwTZ0vg6NkYCg60BS7Tt2EHQb2llwjV_9aqjHW58BTpR7Z_pYP8EBqqqfLEcGCTfGjhXgxn5YDBytjh6OIXgkrK5b8sUhPYo9EHWCmvT3JusTRm-CrodIgfVOsnJLMWXQZim5iXKqiPm3rdmh0EXBdQ9qRU40zMO6LYl0XW2sMDKaKdjeoTJFDPL9RlWeJ4k-ZlXR7uBOamCNbZotxSHl3-DbJJI7TDkWJ9nqH8rj-Dalrpi6CvBvged7sj2ywwLSxrp-l2FDmhY-OUkonBKNNZNc6m5uweJ6De7KJrc-S9DfT2epMhzV
4:59:15 PM - [debug] [alexa-adapter:Alexa] get_user_profile CCHI access_token res {"access_token":"Atza|IwEBIEiRM6UmfMQ-3H5BcUXXbQjU2fHSpPOrruMgqGZYqrQIIcNWGlnUZAP-zAXSvXZwylJfoaPgW_4q99rQZC3aNVmSvWpC1xZFPqYBwTZ0vg6NkYCg60BS7Tt2EHQb2llwjV_9aqjHW58BTpR7Z_pYP8EBqqqfLEcGCTfGjhXgxn5YDBytjh6OIXgkrK5b8sUhPYo9EHWCmvT3JusTRm-CrodIgfVOsnJLMWXQZim5iXKqiPm3rdmh0EXBdQ9qRU40zMO6LYl0XW2sMDKaKdjeoTJFDPL9RlWeJ4k-ZlXR7uBOamCNbZotxSHl3-DbJJI7TDkWJ9nqH8rj-Dalrpi6CvBvged7sj2ywwLSxrp-l2FDmhY-OUkonBKNNZNc6m5uweJ6De7KJrc-S9DfT2epMhzV"}
4:59:16 PM - [debug] [alexa-adapter:Alexa] get_user_profile CCHI profile res {"req":{"method":"GET","url":"https://api.amazon.com/user/profile","headers":{"user-agent":"node-superagent/3.8.3","authorization":"Bearer Atza|IwEBIEiRM6UmfMQ-3H5BcUXXbQjU2fHSpPOrruMgqGZYqrQIIcNWGlnUZAP-zAXSvXZwylJfoaPgW_4q99rQZC3aNVmSvWpC1xZFPqYBwTZ0vg6NkYCg60BS7Tt2EHQb2llwjV_9aqjHW58BTpR7Z_pYP8EBqqqfLEcGCTfGjhXgxn5YDBytjh6OIXgkrK5b8sUhPYo9EHWCmvT3JusTRm-CrodIgfVOsnJLMWXQZim5iXKqiPm3rdmh0EXBdQ9qRU40zMO6LYl0XW2sMDKaKdjeoTJFDPL9RlWeJ4k-ZlXR7uBOamCNbZotxSHl3-DbJJI7TDkWJ9nqH8rj-Dalrpi6CvBvged7sj2ywwLSxrp-l2FDmhY-OUkonBKNNZNc6m5uweJ6De7KJrc-S9DfT2epMhzV","content-type":"application/x-www-form-urlencoded;charset=UTF-8","accept":"application/json"}},"header":{"server":"Server","date":"Wed, 15 Dec 2021 21:59:16 GMT","content-type":"application/json;charset=UTF-8","content-length":"115","connection":"close","x-amz-rid":"WFPKB6T04JMCVTKCCZM4","x-amzn-requestid":"faf75d58-36d0-438e-9db4-b59fc00ca559","x-amz-date":"Wed, 15 Dec 2021 21:59:16 GMT","content-language":"en-US","vary":"Content-Type,Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent","permissions-policy":"interest-cohort=()"},"status":200,"text":"{\"user_id\":\"amzn1.account.AGBCE2ITIGEQNHWMFIRL6QFU3DVQ\",\"name\":\"phillip mobley\",\"email\":\"phillipmobley2@gmail.com\"}"}
4:59:16 PM - [debug] [alexa-adapter:Alexa] get_user_profile CCHI res {"user_id":"amzn1.account.AGBCE2ITIGEQNHWMFIRL6QFU3DVQ","name":"phillip mobley","email":"phillipmobley2@gmail.com"}
4:59:16 PM - [debug] [alexa-adapter:Alexa] phillipmobley2@gmail.com OK
15 Dec 16:59:16 - [error] [alexa-adapter:Alexa] Username phillipmobley2@gmail.com authorized
4:59:16 PM - [debug] [alexa-adapter:Alexa] manage_login_with_amazon_access_token CCHI auth_code {"code":"4f3oWTPfoHxs6w3jjvjy86q6fS9wDCkjxvMdQgvsnqRs","expire_at":1639605676114}
4:59:16 PM - [debug] [alexa-adapter:Alexa] redirect_to_amazon to https://pitangui.amazon.com/api/skill/link/M186UMMFQ858RV?state=A2SAAEAEOi8qOxyMfkg1iA3R-E0ZpAB8DfyZumJL3GaM2NyveoeqVSar8lv6oZfyZIl49blj2uooCS3DFPxQYAQ3NuCJWjpV0DWXRdsfBOUGZDw_Tp4r6icwxKi1Dc2CW3pPeEIYUkx9YNBCjov-FiPzy2_1BpwlLAAmP0-eLpeCqufIWDksKxOA_0Nj6Ez0jQZE3YlTb6WrwQtUEpv5RPvrKwv89zBa-ZXSWK-cUVRbZMnV6t6ZPfB5qthsUn0aO0vkZcneNdN0iKvSRpcf-IQkjvZXoOXmaHVqjmgHxYwDdlkl5gq106iPxO53LrPI94ln2WukSkhZlzMHhdaqTEWPKwT2NIDZZi-2ULNhGHXDoiM0npxlb3f9E-8Cq06XB5csx7z2qBCWJihmfebzOaVl_LJY6i5mvr3WIoOaKuvsgvsYAfJ-UkA9cUgfv-fAcK1oztrM_pTHFP-ewbvd237y1GUh3KZImO3w6Nsp38NPWaNGqC6WkhhJBie0ChSPIrqoPfkbEhXIbQYhXpN9HP1nBjy3hcTl16v1XbZuIBrucTHstkDAQUPsu46zRvMrUEgwZuL55EUi31DM5DqPn4MidhGUYf3ARkRt5SfJbL8QJdIllcE8fOjTfRD4GLu8ozCLaY16AppTJa1szHIk7DJMvic7iNQRjNOA4aTDkb1uFRwD0N5WXU&code=4f3oWTPfoHxs6w3jjvjy86q6fS9wDCkjxvMdQgvsnqRs
4:59:16 PM - [debug] [alexa-adapter:Alexa] token_post
4:59:16 PM - [debug] [alexa-adapter:Alexa] token_post CCHI {"grant_type":"authorization_code","code":"4f3oWTPfoHxs6w3jjvjy86q6fS9wDCkjxvMdQgvsnqRs","client_id":"https://pitangui.amazon.com/","redirect_uri":"https://pitangui.amazon.com/api/skill/link/M186UMMFQ858RV","client_secret":"supersercetpassword"}
15 Dec 16:59:16 - [error] [alexa-adapter:Alexa] token_post authorization_code
4:59:16 PM - [debug] [alexa-adapter:Alexa] writeJson: tokens
4:59:16 PM - [debug] [alexa-adapter:Alexa] writeJson: filename /home/pi/.node-red/alexa-tokens_b6996b92647b12f3.json
4:59:16 PM - [debug] [alexa-adapter:Alexa] writeJson: tokens saved
4:59:16 PM - [debug] [alexa-adapter:Alexa] token_post save_tokens ok
4:59:16 PM - [debug] [alexa-adapter:Alexa] Returns tokens
4:59:16 PM - [debug] [alexa-adapter:Alexa] Returns tokens {"access_token":"Atza|CoyH34nrr5hPwAuyxGfHpoNCviTLTF2MjN5hsSMyBnFU","token_type":"bearer","expires_in":3600,"refresh_token":"Atzr|5CSDAsSP1ZwW7vCxj5ceJixaUoYoPw1aHGTa9bRjwGV5"}
4:59:17 PM - [debug] [alexa-adapter:Alexa] smarthome_post_verify
```

**Comment by ckhmer1** [comment]
Don't enable the feature "Verify the Alexa message", it is used only if You deploy the skill.

**Comment by ckhmer1** [comment]
> Alexa.Authorization





> {'directive': {'header': {'namespace': 'Alexa.Authorization', 'name': 'AcceptGrant', 'messageId': '4501f4ea-21a4-49d5-9aba-9c97cd638004', 'payloadVersion': '3'}, 'payload': {'grant': {'type': 'OAuth2.AuthorizationCode', 'code': 'ANknZGCJTiUAaBeNOomb'}, 'grantee': {'type': 'BearerToken', 'token': 'Atza|4UCCS46wu5PdeeEUBzvF8W7WLPQcZW88RvCecSX3NWLV'}}}}

**Comment by philm001** [comment]
Hello, from the logs, I do see the tokens being exchanged but I do not see the response from the server Here is what I am getting from the token server. As you can see, I am getting the access_token and refresh tokens however, I am not getting the correct response

```
(907e9b1f-45de-4ce1-8da8-a1c97dce05db) Method response body after transformations: 
{
    "access_token": "Atza|B4oLmAn5xWoBFS3CBtHEchhLgkj4Ejg7e7SGxt3aUfjW",
    "token_type": "bearer",
    "expires_in": 3600,
    "refresh_token": "Atzr|BMUKqxYJtEyrNRz6zETTZfs8fmD68qZTHHQku8Fey6EU"
}
```
